### ISSUE TITLE
Feature: User can view Starship data

### ISSUE THREAD

**Issue by BlakexLim** [BlakexLim/Star-Wars-Fleet-Sim#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of starships and add as many as they want to their fleet.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive page that shows the user a list of starships and a working button that adds the starship to the user's fleet.
If it is the first time adding a starship to fleet, then user can fill out an input box for the fleet name and description.

 > Role play as a fleet admiral and build your fleet.
Add starships of different classes and give them a name as well as a description of their role in your fleet.
Create your own lore of squadrons and cruisers in your fleet.
Use your imagination and have fun with it.

## 🖼️ Wireframes
![Screenshot 2024-03-06 095351](https://github.com/BlakexLim/Front-end-project/assets/132517914/88f1e22d-58ed-400e-a394-2f51ac0e0520)
![Screenshot 2024-03-06 095402](https://github.com/BlakexLim/Front-end-project/assets/132517914/5284639f-5f75-4994-9e5d-3905dc5c7c9f)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create html file with a standard HTML skeleton
- [x] In the body, create the HTML for the main page that allows the user to view a list of starships
- [x] Complete the HTML form using the appropriate responsive layout classes
    - [x] write CSS for mobile devices first
    - [x] adjust styling to fluidly adapt to desktop
- [x] Make api call for a list of starships and create a new HTML `li` element for each starship
- [x] Render starship information to the respective variable in the `rundown ` section
- [x] Test the app by clicking starships and confirm each starship has a unique rundown

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application
  - [x] Confirm that functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
