### ISSUE TITLE
Feature: User can add starship

### ISSUE THREAD

**Issue by BlakexLim** [BlakexLim/Star-Wars-Fleet-Sim#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add a starship to the fleet
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Starships can be added to the fleet on the main page, and in the fleet page user will be redirected to main page when pressing + button if fleet is empty
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-13 095147](https://github.com/BlakexLim/Star-Wars-Fleet-Sim/assets/132517914/6f5566fe-3508-4819-908e-3a241090104c)
![Screenshot 2024-03-13 120246](https://github.com/BlakexLim/Star-Wars-Fleet-Sim/assets/132517914/378b8e87-3b95-4bf3-b070-8b33d9d88686)

![Screenshot 2024-03-13 095203](https://github.com/BlakexLim/Star-Wars-Fleet-Sim/assets/132517914/e0b7869c-5b22-45f8-83a2-9fbe13c97fa1)
![Screenshot 2024-03-13 120747](https://github.com/BlakexLim/Star-Wars-Fleet-Sim/assets/132517914/988de773-8196-4469-b883-a8aae0533206)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new HTML body for the fleet page
- [x] Let users know that the fleet is empty if users haven't added starships
- [x] Make a button that will switch the fleet page to the main page
- [x] Create CSS to match wireframes
- [x] Add event listener to button that switches view from fleet to main
    - [x] test to make sure redirection works 
- [x] Add event listener to `Add to fleet` button 
    - [x] event will add starship to fleet page
    - [x] save to local storage so when the user leaves then comes back, fleet is intact
- [x] Make sure page is responsive on mobile and other screen sizes
- [x] User will be able to view all Starships in the fleet
- [x] In data.js file add a `'beforeunload'` event listener to the `window` object that serializes the starship data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of data.js, include a conditional statement that:
    - [x] checks to see if there is a JSON data model stored in localStorage.
    - [x] if there is, parse it and assign it to the  `data` variable so that the user can continue adding entries to the pre-existing 
          data model.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
