### ISSUE TITLE
Feature: User can remove starships 

### ISSUE THREAD

**Issue by BlakexLim** [BlakexLim/Star-Wars-Fleet-Sim#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove starships from the fleet
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Starship will be removed from the fleet when pressing the minus icon 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-13 101044](https://github.com/BlakexLim/Star-Wars-Fleet-Sim/assets/132517914/638d4caa-19f5-4f3d-8bd6-cda55448bdb3)
![Screenshot 2024-03-13 101107](https://github.com/BlakexLim/Star-Wars-Fleet-Sim/assets/132517914/adda70e8-5c0f-4576-82ec-db950919ccef)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add minus icon from font awesome and append it to each new entry
- [x] Add click event listener to minus icon to allow users to delete a starship
    - [x] remove starship from `data` object's `saveFleet` array in `data.ts`
    - [x] remove starship `li` eelement from the DOM
- [x] Conditionally show the empty fleet text if there are no more starships
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
